<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit card_card</name>
   <tag></tag>
   <elementGuidId>dcbd1d32-d81b-43e8-9329-a1cd504c147c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>561edf36-5c40-49f6-8d56-af4e1072bb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e224d6b-b19b-4007-b6e9-fa5548ebe9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b7d75faa-ac49-4e43-acc6-642d4c64d00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>2e7619b9-8889-44d9-a48b-cd47b0ddb5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card&quot;)</value>
      <webElementGuid>ad02f05c-de92-43d9-874a-6b7f01037604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card']</value>
      <webElementGuid>217e405a-6b7f-4649-9891-01d47c914e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderModal']/div/div/div[2]/form/div[4]/input</value>
      <webElementGuid>d358d44b-dfe5-405c-ac9c-8e837f54c5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>eb6b2997-0fce-458d-8440-e063a7b4ca21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'card']</value>
      <webElementGuid>0c5bf6cf-099f-4803-b483-f7070af9eeac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
